REST API
DaryaBN/social-network-study pull request #29
Opened 2023-10-25 17:55 UTC by DaryaBN

2023-10-27 13:05 UTC, burtovoy requested changes

2023-10-27 13:05 UTC, burtovoy commented on app.js
> +  information.rows.forEach((item) => {
Так неправильно делать. Т.е. ты вытаскиваешь все записи потом отбираешь по id. Это нужно прописывать в sql запросе. Т.е. на уровне sql запроса выбрать нужные данные

2023-11-27 07:49 UTC, DaryaBN commented
Я  немного не понимаю, вот так все работает, но в удалении поста и изменении его я не понимаю изменятся ли в базе, так да, но если я потом вызываю базу, что бы проверить, то там без изменений(app.post на 98 строчке я комент оставила), а так как вызывать всю базу и там работать не совсем верно, то зашла в тупик

2023-12-05 08:06 UTC, burtovoy commented
Обсудили доработки

2023-12-05 08:06 UTC, closed without merging